/**
 * A modified subset of the names defined in the VS Code JavaScript language.
 */
export type Name =
  | 'case-clause.expr.esp punctuation.definition.section.case-statement.esp'
  | 'case-clause.expr.esp'
  | 'comment.block.documentation.esp'
  | 'comment.block.esp'
  | 'comment.line.double-slash.esp'
  | 'comment.line.shebang.esp'
  | 'comment.line.triple-slash.directive.esp'
  | 'constant.character.control.regexp'
  | 'constant.character.entity.esp'
  | 'constant.character.escape.backslash.regexp'
  | 'constant.character.escape.esp'
  | 'constant.character.numeric.regexp'
  | 'constant.language.esp'
  | 'constant.numeric.binary.esp'
  | 'constant.numeric.decimal.esp'
  | 'constant.numeric.hex.esp'
  | 'constant.numeric.octal.esp'
  | 'constant.other.character-class.range.regexp'
  | 'constant.other.character-class.regexp'
  | 'constant.other.character-class.set.regexp'
  | 'entity.name.function.esp variable.language.this.esp'
  | 'entity.name.function.esp'
  | 'entity.name.function.tagged-template.esp'
  | 'entity.name.label.esp'
  | 'entity.name.tag.directive.esp'
  | 'entity.name.tag.esp'
  | 'entity.name.tag.namespace.esp'
  | 'entity.name.type.alias.esp'
  | 'entity.name.type.class.esp'
  | 'entity.name.type.enum.esp'
  | 'entity.name.type.interface.esp'
  | 'entity.name.type.esp'
  | 'entity.name.type.module.esp'
  | 'entity.other.attribute-name.directive.esp'
  | 'entity.other.attribute-name.esp'
  | 'entity.other.attribute-name.namespace.esp'
  | 'entity.other.inherited-class.esp'
  | 'invalid.illegal.attribute.esp'
  | 'invalid.illegal.bad-ampersand.esp'
  | 'invalid.illegal.newline.esp'
  | 'keyword.control.esp'
  | 'keyword.generator.asterisk.esp'
  | 'keyword.operator.esp'
  | 'keyword.operator.assignment.esp'
  | 'keyword.other.esp'
  | 'meta.array-binding-pattern-variable.esp'
  | 'meta.array.literal.esp'
  | 'meta.arrow.esp meta.return.type.arrow.esp keyword.operator.type.annotation.esp'
  | 'meta.arrow.esp'
  | 'meta.assertion.look-ahead.regexp'
  | 'meta.assertion.look-behind.regexp'
  | 'meta.assertion.negative-look-ahead.regexp'
  | 'meta.assertion.negative-look-behind.regexp'
  | 'meta.block.esp punctuation.definition.block.esp'
  | 'meta.block.esp'
  | 'meta.brace.round.esp'
  | 'meta.brace.square.esp'
  | 'meta.class.esp'
  | 'meta.decorator.esp'
  | 'meta.definition.function.esp entity.name.function.esp'
  | 'meta.definition.method.esp entity.name.function.esp'
  | 'meta.definition.property.esp entity.name.function.esp'
  | 'meta.definition.property.esp variable.object.property.esp'
  | 'meta.definition.variable.esp entity.name.function.esp'
  | 'meta.definition.variable.esp variable.other.constant.esp entity.name.function.esp'
  | 'meta.definition.variable.esp variable.other.constant.esp'
  | 'meta.definition.variable.esp variable.other.readwrite.esp'
  | 'meta.delimiter.decimal.period.esp'
  | 'meta.enum.declaration.esp'
  | 'meta.export.default.esp'
  | 'meta.export.esp'
  | 'meta.field.declaration.esp'
  | 'meta.function-call.esp keyword.operator.definiteassignment.esp'
  | 'meta.function-call.esp punctuation.accessor.optional.esp'
  | 'meta.function-call.esp'
  | 'meta.function.expression.esp'
  | 'meta.function.esp'
  | 'meta.group.assertion.regexp'
  | 'meta.group.regexp'
  | 'meta.import-equals.external.esp'
  | 'meta.import-equals.internal.esp'
  | 'meta.import.esp'
  | 'meta.indexer.declaration.esp'
  | 'meta.indexer.mappedtype.declaration.esp'
  | 'meta.interface.esp'
  | 'meta.method.declaration.esp'
  | 'meta.namespace.declaration.esp'
  | 'meta.object-binding-pattern-variable.esp'
  | 'meta.object-literal.key.esp punctuation.separator.key-value.esp'
  | 'meta.object-literal.key.esp'
  | 'meta.object.member.esp meta.object-literal.key.esp'
  | 'meta.object.member.esp'
  | 'meta.object.type.esp'
  | 'meta.objectliteral.esp'
  | 'meta.parameter.object-binding-pattern.esp'
  | 'meta.parameters.esp'
  | 'meta.paramter.array-binding-pattern.esp'
  | 'meta.return.type.arrow.esp'
  | 'meta.return.type.esp'
  | 'meta.tag.attributes.esp'
  | 'meta.tag.esp'
  | 'meta.tag.without-attributes.esp'
  | 'meta.template.expression.esp'
  | 'meta.type.annotation.esp'
  | 'meta.type.constructor.esp keyword.control.new.esp'
  | 'meta.type.constructor.esp storage.modifier.esp'
  | 'meta.type.constructor.esp'
  | 'meta.type.declaration.esp'
  | 'meta.type.function.esp'
  | 'meta.type.function.return.esp'
  | 'meta.type.infer.esp'
  | 'meta.type.parameters.esp punctuation.definition.typeparameters.begin.esp'
  | 'meta.type.parameters.esp punctuation.definition.typeparameters.end.esp'
  | 'meta.type.parameters.esp'
  | 'meta.type.paren.cover.esp'
  | 'meta.type.tuple.esp'
  | 'meta.var-single-variable.expr.esp'
  | 'meta.var.expr.esp'
  | 'new.expr.esp'
  | 'punctuation.esp'
  | 'source.embedded.esp'
  | 'storage.modifier.async.esp'
  | 'storage.modifier.esp'
  | 'storage.type.class.esp'
  | 'storage.type.enum.esp'
  | 'storage.type.function.arrow.esp'
  | 'storage.type.function.esp'
  | 'storage.type.interface.esp'
  | 'storage.type.internaldeclaration.esp'
  | 'storage.type.esp'
  | 'storage.type.namespace.esp'
  | 'storage.type.numeric.bigint.esp'
  | 'storage.type.property.esp'
  | 'storage.type.type.esp'
  | 'string.quoted.double.esp'
  | 'string.quoted.single.esp'
  | 'string.regexp.esp'
  | 'string.template.esp'
  | 'support.class.component.esp'
  | 'support.class.esp'
  | 'support.class.promise.esp'
  | 'support.constant.esp'
  | 'support.type.builtin.esp'
  | 'support.type.object.module.esp'
  | 'support.type.primitive.esp'
  | 'support.variable.property.importmeta.esp'
  | 'support.variable.property.esp'
  | 'support.variable.property.target.esp'
  | 'switch-block.expr.esp'
  | 'switch-expression.expr.esp'
  | 'switch-statement.expr.esp'
  | 'variable.language.arguments.esp'
  | 'variable.language.super.esp'
  | 'variable.language.this.esp'
  | 'variable.object.property.esp'
  | 'variable.other.constant.esp'
  | 'variable.other.constant.object.esp'
  | 'variable.other.constant.object.property.esp'
  | 'variable.other.constant.property.esp'
  | 'variable.other.enummember.esp'
  | 'variable.other.object.esp'
  | 'variable.other.object.property.esp'
  | 'variable.other.property.esp'
  | 'variable.other.readwrite.esp'
  | 'variable.other.regexp'
  | 'variable.parameter.esp variable.language.this.esp'
  | 'variable.parameter.esp';
