import {
  ConstantKeyword,
  ControlKeyword,
  Operator,
  Punctuation,
} from '../esp-grammar';
import { Name } from './names';

export const constantKeywordNames: Record<ConstantKeyword, Name> = {
  false: 'constant.language.boolean.false.esp',
  Infinity: 'constant.language.infinity.esp',
  NaN: 'constant.language.nan.esp',
  null: 'constant.language.null.esp',
  true: 'constant.language.boolean.true.esp',
  undefined: 'constant.language.undefined.esp',
};

export const controlKeywordNames: Record<ControlKeyword, Name> = {
  break: 'keyword.control.loop.esp',
  const: 'storage.type.esp',
  continue: 'keyword.control.loop.esp',
  do: 'keyword.control.loop.esp',
  else: 'keyword.control.conditional.esp',
  export: 'keyword.control.export.esp',
  for: 'keyword.control.loop.esp',
  if: 'keyword.control.conditional.esp',
  import: 'keyword.control.import.esp',
  let: 'storage.type.esp',
  match: 'keyword.control.switch.esp',
  new: 'keyword.operator.new.esp',
  return: 'keyword.control.flow.esp',
  throw: 'keyword.control.trycatch.esp',
  while: 'keyword.control.loop.esp',
};

export const operatorNames: Record<Operator, Name> = {
  '--': 'keyword.operator.decrement.esp',
  '-': 'keyword.operator.assignment.compound.esp',
  '-=': 'keyword.operator.arithmetic.esp',
  '!': 'keyword.operator.logical.esp',
  '!=': 'keyword.operator.comparison.esp',
  '??': 'keyword.operator.logical.esp',
  '??=': 'keyword.operator.logical.esp',
  '?': 'keyword.operator.ternary.esp',
  '*': 'keyword.operator.arithmetic.esp',
  '**': 'keyword.operator.arithmetic.esp',
  '**=': 'keyword.operator.assignment.compound.esp',
  '*=': 'keyword.operator.assignment.compound.esp',
  '/': 'keyword.operator.arithmetic.esp',
  '/=': 'keyword.operator.assignment.compound.esp',
  '&': 'keyword.operator.bitwise.esp',
  '&&': 'keyword.operator.logical.esp',
  '&&=': 'keyword.operator.assignment.compound.esp',
  '&=': 'keyword.operator.assignment.compound.bitwise.esp',
  '%': 'keyword.operator.arithmetic.esp',
  '%=': 'keyword.operator.assignment.compound.esp',
  '^': 'keyword.operator.bitwise.esp',
  '^=': 'keyword.operator.assignment.compound.bitwise.esp',
  '+': 'keyword.operator.arithmetic.esp',
  '++': 'keyword.operator.increment.esp',
  '+=': 'keyword.operator.assignment.compound.esp',
  '<': 'keyword.operator.relational.esp',
  '<<': 'keyword.operator.bitwise.shift.esp',
  '<<=': 'keyword.operator.assignment.compound.bitwise.esp',
  '<=': 'keyword.operator.relational.esp',
  '=': 'keyword.operator.assignment.esp',
  '==': 'keyword.operator.comparison.esp',
  '>': 'keyword.operator.relational.esp',
  '>=': 'keyword.operator.relational.esp',
  '>>': 'keyword.operator.bitwise.shift.esp',
  '>>=': 'keyword.operator.assignment.compound.bitwise.esp',
  '>>>': 'keyword.operator.bitwise.shift.esp',
  '>>>=': 'keyword.operator.assignment.compound.bitwise.esp',
  '|': 'keyword.operator.bitwise.esp',
  '|=': 'keyword.operator.assignment.compound.bitwise.esp',
  '||': 'keyword.operator.logical.esp',
  '||=': 'keyword.operator.assignment.compound.esp',
  '~': 'keyword.operator.bitwise.esp',
};

export const punctuationNames: Record<Punctuation, Name | null> = {
  ',': 'punctuation.separator.comma.esp',
  ';': 'punctuation.terminator.statement.esp',
  ':': null,
  '.': 'punctuation.accessor.esp',
  '(': 'meta.brace.round.esp',
  ')': 'meta.brace.round.esp',
  '[': 'meta.brace.square.esp',
  ']': 'meta.brace.square.esp',
  '{': 'punctuation.definition.block.esp',
  '}': 'punctuation.definition.block.esp',
  '#': null,
};
