export const enum NodeType {
  ArrayLiteral = 'ArrayLiteral',
  AssignmentExpression = 'AssignmentExpression',
  BinaryExpression = 'BinaryExpression',
  BlockStatement = 'BlockStatement',
  BreakStatement = 'BreakStatement',
  CallExpression = 'CallExpression',
  ComputedMemberExpression = 'ComputedMemberExpression',
  ConditionalExpression = 'ConditionalExpression',
  ContinueStatement = 'ContinueStatement',
  DoWhileStatement = 'DoWhileStatement',
  ExpressionStatement = 'ExpressionStatement',
  Identifier = 'Identifier',
  IfStatement = 'IfStatement',
  Literal = 'Literal',
  NewExpression = 'NewExpression',
  ObjectLiteral = 'ObjectLiteral',
  Property = 'Property',
  ReturnStatement = 'ReturnStatement',
  StaticMemberExpression = 'StaticMemberExpression',
  ThrowStatement = 'ThrowStatement',
  UnaryExpression = 'UnaryExpression',
  UpdateExpression = 'UpdateExpression',
  VariableDeclaration = 'VariableDeclaration',
  WhileStatement = 'WhileStatement',
}
