export const enum NodeType {
  Arguments = 'Arguments',
  ArrayLiteral = 'ArrayLiteral',
  AssignmentExpression = 'AssignmentExpression',
  BinaryExpression = 'BinaryExpression',
  CallExpression = 'CallExpression',
  ComputedMemberExpression = 'ComputedMemberExpression',
  Identifier = 'Identifier',
  Literal = 'Literal',
  NewExpression = 'NewExpression',
  ObjectLiteral = 'ObjectLiteral',
  Property = 'Property',
  StaticMemberExpression = 'StaticMemberExpression',
  UnaryExpression = 'UnaryExpression',
  UpdateExpression = 'UpdateExpression',
}
